/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * NOTE: Normally auto-generated by `npx convex dev` — hand-written here to
 * match Convex's own template exactly, so the app builds before you've
 * connected a real deployment. `npx convex dev` will regenerate this file
 * against your actual deployment; that's expected.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
import { anyApi } from 'convex/server';

export const api = anyApi;
export const internal = anyApi;
