/* eslint-disable */
/**
 * Generated utilities for implementing server-side Convex query and
 * mutation functions.
 *
 * NOTE: This file is normally auto-generated by `npx convex dev`. It has
 * been hand-written here (matching Convex's own codegen template exactly)
 * so the project type-checks and builds before you've connected a real
 * Convex deployment. Once you run `npx convex dev` for the first time,
 * Convex will regenerate this folder itself — that's expected and fine.
 */
import {
  actionGeneric,
  httpActionGeneric,
  queryGeneric,
  mutationGeneric,
  internalActionGeneric,
  internalMutationGeneric,
  internalQueryGeneric,
} from 'convex/server';

export const query = queryGeneric;
export const internalQuery = internalQueryGeneric;
export const mutation = mutationGeneric;
export const internalMutation = internalMutationGeneric;
export const action = actionGeneric;
export const internalAction = internalActionGeneric;
export const httpAction = httpActionGeneric;
