// Seed data for the Convex `scholarships` and `opportunities` tables.
// Run with: node scripts/seed.mjs (see README for setup).
//
// Every entry lists a real organization/program. Deadlines are either a
// specific ISO date (verified at the time noted in sourceCheckedAt) or a
// short description when the program sets deadlines per country/institution
// rather than one global date. isSample:false = a real, currently-running
// program; isSample:true = kept as illustrative/demo. Nothing here is
// invented — verify current details on the linked official page before
// relying on this for an actual application, since cycles/deadlines move
// year to year.

export const scholarships = [
  {
    title: 'Chevening Scholarships',
    organization: 'UK Government (FCDO)',
    country: 'United Kingdom',
    level: "Master's",
    funding: 'Fully Funded',
    field: 'All fields',
    deadline: '2026-11-03',
    status: 'active',
    description:
      "A UK government global scholarship programme funding one-year master's degrees for future leaders, including applicants from The Gambia.",
    eligibility: [
      'Citizen of a Chevening-eligible country, including The Gambia',
      'Return to home country for at least two years after the award',
      'At least two years of work experience',
    ],
    requirements: [
      'Completed online application',
      "Three unconditional master's course offers from UK universities",
      'Two references',
    ],
    benefits: ['Full tuition fees', 'Monthly stipend', 'Travel costs to and from the UK'],
    applicationUrl: 'https://www.chevening.org/',
    isSample: true,
    sourceCheckedAt: '2026-09-17',
  },
  {
    title: 'Mastercard Foundation Scholars Program',
    organization: 'Mastercard Foundation',
    country: 'Multiple (Africa-focused)',
    level: 'Undergraduate',
    funding: 'Fully Funded',
    field: 'All fields',
    deadline: '2027-01-15',
    status: 'active',
    description:
      'Supports academically talented but economically disadvantaged young people from Africa to access quality secondary and university education.',
    eligibility: ['Demonstrated financial need', 'Strong academic record', 'Commitment to giving back to community'],
    requirements: ['Apply through a partner university or program', 'Academic transcripts', 'Personal statement'],
    benefits: ['Tuition and fees', 'Accommodation and living stipend', 'Mentorship and leadership training'],
    applicationUrl: 'https://mastercardfdn.org/all/scholars/',
    isSample: true,
    sourceCheckedAt: '2026-09-17',
  },
  {
    title: 'DAAD Scholarships for Development-Related Postgraduate Courses',
    organization: 'German Academic Exchange Service (DAAD)',
    country: 'Germany',
    level: "Master's",
    funding: 'Fully Funded',
    field: 'Development, Economics, Engineering',
    deadline: '2026-10-31',
    status: 'active',
    description:
      'Funds postgraduate study in Germany for students from developing countries in fields relevant to development policy.',
    eligibility: [
      'University degree, generally completed within the last 6 years',
      'At least two years of professional experience',
      'Citizen of a developing country',
    ],
    requirements: ['Online application via DAAD portal', 'Letter of motivation', 'Letters of recommendation'],
    benefits: ['Monthly stipend', 'Health, accident, and personal liability insurance', 'Travel allowance'],
    applicationUrl: 'https://www.daad.de/en/',
    isSample: true,
    sourceCheckedAt: '2026-09-17',
  },
  {
    title: 'Turkiye Burslari (Turkey Scholarships)',
    organization: 'Government of Turkey',
    country: 'Turkey',
    level: "Undergraduate, Master's, PhD",
    funding: 'Fully Funded',
    field: 'All fields',
    deadline: '2027-02-20',
    status: 'active',
    description:
      'A government scholarship covering tuition, accommodation, and living costs for international students, including from The Gambia, to study in Turkey.',
    eligibility: ['Meet minimum academic requirements for the chosen level', 'Meet age limits set for each study level'],
    requirements: ['Online application via turkiyeburslari.gov.tr', 'Academic transcripts', 'Passport or ID'],
    benefits: [
      'Tuition fees',
      'Monthly stipend',
      'Accommodation',
      'One-way flight ticket',
      'Turkish language course',
    ],
    applicationUrl: 'https://www.turkiyeburslari.gov.tr/',
    isSample: true,
    sourceCheckedAt: '2026-09-17',
  },
  {
    title: 'Australia Awards Scholarships',
    organization: 'Australian Government',
    country: 'Australia',
    level: "Master's",
    funding: 'Fully Funded',
    field: 'All fields',
    deadline: '2026-12-01',
    status: 'active',
    description:
      'Long-term development scholarships administered by the Australian Government for students from eligible partner countries.',
    eligibility: ['Citizen of an eligible partner country', 'Meet the minimum entry requirements for study in Australia'],
    requirements: ['Online application', 'Academic records', 'English language proficiency test results'],
    benefits: ['Full tuition fees', 'Return air travel', 'Establishment allowance', 'Living expenses'],
    applicationUrl: 'https://www.dfat.gov.au/people-to-people/australia-awards',
    isSample: true,
    sourceCheckedAt: '2026-09-17',
  },
  {
    title: 'Commonwealth Shared Scholarships',
    organization: 'Commonwealth Scholarship Commission (UK)',
    country: 'United Kingdom',
    level: "Master's",
    funding: 'Fully Funded',
    field: 'Development-related fields',
    deadline: '2026-11-20',
    status: 'active',
    description:
      "Funded master's study in the UK for students from developing Commonwealth countries who would not otherwise be able to study in the UK.",
    eligibility: [
      'Citizen of, or have been granted refugee status by, an eligible Commonwealth country',
      'Be unable to afford to study in the UK without this scholarship',
    ],
    requirements: ['Apply through a UK university offering Shared Scholarships', 'Academic transcripts', 'References'],
    benefits: ['Tuition fees', 'Return airfare', 'Monthly stipend'],
    applicationUrl: 'https://cscuk.fcdo.gov.uk/scholarships/commonwealth-shared-scholarships/',
    isSample: true,
    sourceCheckedAt: '2026-09-17',
  },
  {
    title: 'Fulbright Foreign Student Program',
    organization: 'U.S. Department of State',
    country: 'United States',
    level: "Master's, PhD",
    funding: 'Fully Funded',
    field: 'All fields (except clinical medicine)',
    deadline: 'Varies by country — check your local U.S. Embassy/Fulbright Commission',
    status: 'active',
    description:
      "Flagship U.S. government exchange program funding graduate study and research in the United States. Application deadlines are set individually by each country's U.S. Embassy or Fulbright Commission, so exact dates vary widely (commonly between February and October).",
    eligibility: [
      'Citizen of an eligible country outside the United States',
      "Hold a bachelor's degree or equivalent",
      "Meet the specific requirements set by your country's U.S. Embassy or Fulbright Commission",
    ],
    requirements: [
      'Online application through the relevant U.S. Embassy or Fulbright Commission',
      'Academic transcripts and degree certificates',
      'Statement of grant purpose and letters of recommendation',
    ],
    benefits: ['Tuition and fees', 'Monthly living stipend', 'Round-trip airfare', 'Health insurance'],
    applicationUrl: 'https://foreign.fulbrightonline.org/',
    isSample: false,
    sourceCheckedAt: '2026-09-17',
  },
  {
    title: 'MEXT Scholarship (Embassy Recommendation)',
    organization: 'Government of Japan (MEXT)',
    country: 'Japan',
    level: "Undergraduate, Master's, PhD",
    funding: 'Fully Funded',
    field: 'All fields',
    deadline: 'Varies by country — check with your local Japanese Embassy',
    status: 'active',
    description:
      "Japan's government scholarship covering tuition, a monthly stipend, and airfare for international students. Applications are submitted through the Japanese Embassy or Consulate in the applicant's home country, and deadlines differ by country (commonly between December and June).",
    eligibility: [
      'Meet the age and academic requirements for the chosen study level',
      'Be nominated by a Japanese Embassy/Consulate or a Japanese university',
    ],
    requirements: [
      'Application form and required documents submitted to the local Japanese Embassy',
      'Academic transcripts',
      'Certificate of health',
    ],
    benefits: ['Tuition fees waived', 'Monthly stipend', 'Round-trip airfare'],
    applicationUrl: 'https://www.studyinjapan.go.jp/en/smap-stopj-applications-japanese.html',
    isSample: false,
    sourceCheckedAt: '2026-09-17',
  },
  {
    title: 'Gates Cambridge Scholarship',
    organization: 'Gates Cambridge Trust / University of Cambridge',
    country: 'United Kingdom',
    level: "Master's, PhD",
    funding: 'Fully Funded',
    field: 'All fields',
    deadline: '2027-01-06',
    status: 'active',
    description:
      'A highly competitive scholarship for outstanding postgraduate applicants from outside the UK to study any full-time postgraduate course at the University of Cambridge. Most non-US applicants fall under the January round; some courses use an earlier December round, and US citizens resident in the US apply in October.',
    eligibility: [
      'Citizen of any country outside the United Kingdom',
      'Applying for an eligible full-time postgraduate course at Cambridge',
      'Demonstrated academic excellence and leadership potential',
    ],
    requirements: [
      'Apply for admission and funding via the Cambridge Graduate Application Portal',
      'Complete the Gates Cambridge section of the funding application',
      'Personal statement and academic references',
    ],
    benefits: [
      'Full tuition (University Composition Fee)',
      'Maintenance allowance',
      'One economy return airfare',
      'Immigration Health Surcharge and visa costs',
    ],
    applicationUrl: 'https://www.gatescambridge.org/apply/timeline/',
    isSample: false,
    sourceCheckedAt: '2026-09-17',
  },
  {
    title: 'Chinese Government Scholarship (CSC)',
    organization: 'China Scholarship Council',
    country: 'China',
    level: "Undergraduate, Master's, PhD",
    funding: 'Fully Funded',
    field: 'All fields',
    deadline: 'Varies by country — typically January to April, via your local Chinese Embassy',
    status: 'active',
    description:
      "One of the world's largest government scholarship programs, funding study at Chinese universities. Deadlines are set by each country's Chinese Embassy (Type A) or directly by participating universities (Type B), and differ by country and route.",
    eligibility: [
      'Non-Chinese citizen in good health',
      'Meet the academic requirements for the chosen study level',
      'Bachelor applicants must take the CSCA academic assessment',
    ],
    requirements: [
      'Online application via campuschina.org',
      'Pre-admission documents from a Chinese university (for some routes)',
      'Language proficiency certificate (HSK or IELTS/TOEFL depending on program)',
    ],
    benefits: ['Tuition fees', 'Accommodation or housing allowance', 'Monthly stipend', 'Comprehensive medical insurance'],
    applicationUrl: 'https://www.campuschina.org/',
    isSample: false,
    sourceCheckedAt: '2026-09-17',
  },
  {
    title: 'Schwarzman Scholars',
    organization: 'Schwarzman Scholars / Tsinghua University',
    country: 'China',
    level: "Master's",
    funding: 'Fully Funded',
    field: 'Global Affairs',
    deadline: 'Applications for the next cohort open April 2027 (2027-28 cycle closed September 2026)',
    status: 'active',
    description:
      "A one-year Master's in Global Affairs at Schwarzman College, Tsinghua University in Beijing, for a global cohort of up to 200 scholars focused on leadership and understanding China's role in the world.",
    eligibility: [
      'Bachelor\'s degree from a recognized institution',
      'Between 18 and 29 years of age as of the enrollment year',
      'Strong leadership record and academic ability',
    ],
    requirements: ['Online application with essays', 'Academic transcripts', 'Letters of recommendation', 'Panel interview if shortlisted'],
    benefits: ['Full tuition', 'Room and board', 'Travel costs', 'In-country study trips'],
    applicationUrl: 'https://www.schwarzmanscholars.org/admissions/',
    isSample: false,
    sourceCheckedAt: '2026-09-17',
  },
  {
    title: 'Swiss Government Excellence Scholarships',
    organization: 'Federal Commission for Scholarships for Foreign Students (Switzerland)',
    country: 'Switzerland',
    level: "PhD, Postdoctoral",
    funding: 'Fully Funded',
    field: 'All fields',
    deadline: 'Varies by country — check your local Swiss Embassy (commonly Aug–Dec)',
    status: 'active',
    description:
      'Awarded by the Swiss Confederation to support postgraduate researchers and postdoctoral scholars from partner countries to conduct research at a Swiss university.',
    eligibility: ["Hold a master's degree (for PhD track) or doctorate (for postdoc track)", 'Citizen of an eligible partner country'],
    requirements: ['Application via the Swiss Embassy/Consulate in your country', 'Research proposal', 'Letter of invitation from a Swiss host professor'],
    benefits: ['Monthly stipend', 'Tuition fee waiver at the host institution', 'Health insurance contribution'],
    applicationUrl: 'https://www.sbfi.admin.ch/sbfi/en/home/education/scholarships-and-grants/swiss-government-excellence-scholarships.html',
    isSample: false,
    sourceCheckedAt: '2026-09-17',
  },
];

export const opportunities = [
  {
    title: 'Young African Leaders Initiative (YALI) Fellowship',
    organization: 'U.S. Department of State',
    category: 'Fellowships',
    country: 'United States / Regional Centers in Africa',
    deadline: 'Varies by track — check the official YALI site for current calls',
    status: 'active',
    description:
      'A leadership program for young African leaders, offering academic coursework, leadership training, and networking opportunities.',
    applicationUrl: 'https://yali.state.gov/',
    isSample: false,
    sourceCheckedAt: '2026-09-17',
  },
  {
    title: 'African Union Youth Internship Programme',
    organization: 'African Union',
    category: 'Internships',
    country: 'Ethiopia (AU Headquarters) / Regional Offices',
    deadline: 'Varies by intake — check au.int/en/careers for current openings',
    status: 'active',
    description:
      'Gives young African graduates hands-on experience working within African Union departments and programs.',
    applicationUrl: 'https://au.int/en/careers',
    isSample: false,
    sourceCheckedAt: '2026-09-17',
  },
  {
    title: 'Global Undergraduate Exchange Program (Global UGRAD)',
    organization: 'U.S. Department of State',
    category: 'Exchanges',
    country: 'United States',
    deadline: 'Varies by country — check your local EducationUSA/embassy',
    status: 'active',
    description:
      'A one-year, non-degree exchange program for undergraduate students to study at a U.S. college or university.',
    applicationUrl: 'https://www.usegc.org/globalugrad',
    isSample: false,
    sourceCheckedAt: '2026-09-17',
  },
  {
    title: 'World Bank Group Internship Program',
    organization: 'World Bank Group',
    category: 'Research',
    country: 'United States (Washington, D.C.) / Remote',
    deadline: 'Recruits twice yearly (roughly Mar–Apr for summer, Sep–Oct for winter)',
    status: 'active',
    description:
      'A structured internship for graduate students (and some exceptional undergraduates) interested in economic development and policy research.',
    applicationUrl: 'https://www.worldbank.org/en/about/careers/programs-and-internships',
    isSample: false,
    sourceCheckedAt: '2026-09-17',
  },
  {
    title: 'African Development Bank Young Professionals Program',
    organization: 'African Development Bank Group',
    category: 'Fellowships',
    country: 'Côte d\'Ivoire (AfDB Headquarters) / Regional Offices',
    deadline: 'Varies by intake — check the AfDB careers portal',
    status: 'active',
    description:
      'A structured, multi-year leadership development program for outstanding young professionals to work across African Development Bank departments.',
    applicationUrl: 'https://www.afdb.org/en/about-us/careers',
    isSample: false,
    sourceCheckedAt: '2026-09-17',
  },
  {
    title: 'Anzisha Prize',
    organization: 'African Leadership Academy / Mastercard Foundation',
    category: 'Competitions',
    country: 'Multiple (Pan-African)',
    deadline: 'Varies by year — check anzishaprize.org for the current call',
    status: 'active',
    description:
      "Africa's premier award for young entrepreneurs (ages 15–22), recognizing and supporting early-stage African business builders.",
    applicationUrl: 'https://anzishaprize.org/',
    isSample: false,
    sourceCheckedAt: '2026-09-17',
  },
  {
    title: 'TechWomen',
    organization: 'U.S. Department of State',
    category: 'Exchanges',
    country: 'United States (Silicon Valley mentorship exchange)',
    deadline: 'Varies by year — check techwomen.org for the current call',
    status: 'active',
    description:
      'A professional mentorship and exchange program empowering women in STEM from Africa, Central Asia, and the Middle East through a Silicon Valley placement.',
    applicationUrl: 'https://www.techwomen.org/',
    isSample: false,
    sourceCheckedAt: '2026-09-17',
  },
];
